replicaCount: 1

image:
  repository: matheshwar/go-web-app
  pullPolicy: IfNotPresent
  tag: "10016307834"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

